/*
 * generated by Xtext 2.10.0
 */
package de.rowlo.testgenerator.testdsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class TestDSLStandaloneSetup extends TestDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new TestDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
